# Generated by Django 4.1.5 on 2023-01-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0002_contact_news_product_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
