# Generated by Django 4.1.5 on 2023-01-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0003_alter_news_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
