# Generated by Django 4.1.5 on 2023-01-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0004_alter_news_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBase',
            fields=[
                ('newsBase_id', models.AutoField(primary_key=True, serialize=False)),
                ('newsBase_name', models.CharField(blank=True, max_length=100, null=True)),
                ('newsBase_image', models.ImageField(upload_to='media/')),
                ('newsBase_description', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('productBase_id', models.AutoField(primary_key=True, serialize=False)),
                ('productBase_name', models.CharField(blank=True, max_length=100, null=True)),
                ('productBase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('productBase_image', models.ImageField(upload_to='media/')),
                ('productBase_description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
